app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("overtime/", include("overtime.urls", namespace="overtime")),
    path('accounts/', include('allauth.urls')),
    path("meals/", include("meals.urls", namespace="meals")),
    path("forms/", include("forms.urls", namespace="forms")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/overtime/urls.py
from django.urls import path

from . import views

app_name = "overtime"

urlpatterns = [
    path("", views.TimeSheetListView.as_view(), name="time-sheet-list"),
    path("create/", views.TimeSheetCreateView.as_view(), name="time-sheet-create"),
    path(
        "pending-approval/",
        views.TimeSheetPendingApprovalListView.as_view(),
        name="time-sheet-pending-approval",
    ),
    # path(
    #     "filter-list/",
    #     views.TimeSheetFilterListView.as_view(),
    #     name="time-sheet-filter-list",
    # ),
    path(
        "update/<int:pk>/",
        views.TimeSheetUpdateView.as_view(),
        name="time-sheet-update",
    ),
    path(
        "delete/<int:pk>/",
        views.TimeSheetDeleteView.as_view(),
        name="time-sheet-delete",
    ),
]

app/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("users/", views.UserListView.as_view(), name="user-list"),
    path("userprofiles/", views.UserProfileListView.as_view(), name="user-profile-list"),
    path("user/<int:pk>/", views.UserUpdateView.as_view(), name="user-update"),
    path(
        "user-profile/<slug:slug>/<int:pk>/",
        views.UserProfileUpdateView.as_view(),
        name="user-profile-update",
    ),
]

app/templates/components/footer.html
<div class="container">
    <footer
        class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
        <div class="col-md-4 d-flex align-items-center">
            <a href="/"
                class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
                <svg class="bi"
                    width="30"
                    height="24">
                    <use xlink:href="#bootstrap" />
                </svg>
            </a>
            <span class="mb-3 mb-md-0 text-muted">&copy; {% now "Y" %} <a
                    class="text-dark"
                    href="https://swelanauguste.digital/"
                    target="_blank">kingship</a></span>
        </div>

        <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#twitter" />
                    </svg></a></li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#instagram" />
                    </svg></a></li>
            <li class="ms-3"><a class="text-muted"
                    href="#"><svg class="bi"
                        width="24"
                        height="24">
                        <use xlink:href="#facebook" />
                    </svg></a></li>
        </ul>
    </footer>
</div>

app/templates/components/messages.html
{% if messages %}

<div class="container mt-3">
    {% for message in messages %}
    {% if message.tags %}
    <div id="alert-message"
        class="alert alert-{{ message.tags }} show shadow-lg mb-5 rounded alert-message"
        role="alert">
        {% endif %}
        <strong id="alert-message-1">{{ message }}</strong>
        {% endfor %}
    </div>
{% endif %}

app/templates/components/nav_bar.html
<div class="mb-5">
    <nav class="navbar navbar-dark bg-dark fixed-top">

        <div class="container-fluid">
            <a class="navbar-brand"
                href="/">Online Forms</a>
            <a class="navbar-brand"
                href="{{ request.user.profile.get_absolute_url}}">{{request.user.profile.first_name}}</a>
            <span class="text-white"
                data-bs-toggle="offcanvas"
                data-bs-target="#offcanvasNavbar"
                aria-controls="offcanvasNavbar">
                <i class="material-symbols-outlined fs-2 mx-3">
                    expand_circle_down
                </i>
            </span>
            <div class="offcanvas offcanvas-end"
                tabindex="-1"
                id="offcanvasNavbar"
                aria-labelledby="offcanvasNavbarLabel">
                <div class="offcanvas-header">
                    <h5 class="offcanvas-title"
                        id="offcanvasNavbarLabel">Online Support</h5>
                    <button type="button"
                        class="btn-close"
                        data-bs-dismiss="offcanvas"
                        aria-label="Close"></button>
                </div>
                <div class="offcanvas-body">
                    <ul
                        class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                aria-current="page"
                                href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                href="{% url 'overtime:time-sheet-list' %}">Overtime</a>
                        </li>

                        {% if request.user.is_admin %}
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                href="{% url 'users:user-list' %}">Users</a>
                        </li>
                        {% endif %}
                        {% if request.user.is_supervisor %}
                        <li class="nav-item">
                            <a class="nav-link text-dark"
                                href="{% url 'overtime:time-sheet-pending-approval' %}">Pending
                                Approval</a>
                        </li>
                        {% endif %}


                        <!-- <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle"
                                href="#"
                                id="offcanvasNavbarDropdown"
                                role="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu"
                                aria-labelledby="offcanvasNavbarDropdown">
                                <li><a class="dropdown-item"
                                        href="#">Action</a></li>
                                <li><a class="dropdown-item"
                                        href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item"
                                        href="#">Something else here</a></li>
                            </ul>
                        </li> -->
                    </ul>
                    <!-- <form class="d-flex"
                        role="search">
                        <input class="form-control me-2"
                            type="search"
                            placeholder="Search"
                            aria-label="Search">
                        <button class="btn btn-outline-success"
                            type="submit">Search</button>
                    </form> -->
                </div>
            </div>
        </div>
    </nav>
</div>

app/templates/components/pagination.html
<div class="text-end">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>