app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("overtime/", include("overtime.urls", namespace="overtime")),
    path('accounts/', include('allauth.urls')),
    path("meals/", include("meals.urls", namespace="meals")),
    path("forms/", include("forms.urls", namespace="forms")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/overtime/urls.py
from django.urls import path

from . import views

app_name = "overtime"

urlpatterns = [
    path("", views.TimeSheetListView.as_view(), name="time-sheet-list"),
    path("create/", views.TimeSheetCreateView.as_view(), name="time-sheet-create"),
    path(
        "pending-approval/",
        views.TimeSheetPendingApprovalListView.as_view(),
        name="time-sheet-pending-approval",
    ),
    # path(
    #     "filter-list/",
    #     views.TimeSheetFilterListView.as_view(),
    #     name="time-sheet-filter-list",
    # ),
    path(
        "update/<int:pk>/",
        views.TimeSheetUpdateView.as_view(),
        name="time-sheet-update",
    ),
    path(
        "delete/<int:pk>/",
        views.TimeSheetDeleteView.as_view(),
        name="time-sheet-delete",
    ),
]

app/overtime/models.py
from datetime import datetime
from decimal import Decimal

from django.db import models
from django.urls import reverse
from users.models import User


class Multiplier(models.Model):
    multiplier = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ("multiplier",)

    def __str__(self):
        return f"{self.multiplier}"


class TimeSheet(models.Model):
    employee = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    date = models.DateField()
    reason = models.TextField("reason for overtime")
    start_time = models.TimeField(default="16:30:00")
    end_time = models.TimeField(default="18:30:00")
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="time_sheet_approved_by",
        blank=True,
    )
    multiplier = models.ForeignKey(Multiplier, on_delete=models.CASCADE)
    is_verified = models.BooleanField(default=False)
    verified_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="time_sheet_verified_by",
        blank=True,
    )
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="time_sheet_created_by",
    )

    updated_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        related_name="time_sheet_updated_by",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    # def get_absolute_url(self):
    #     return reverse("overtime:overtime-detail", kwargs={"pk": self.pk})

    @property
    def time_diff(self):
        return (
            datetime.strptime(str(self.end_time), "%H:%M:%S")
            - datetime.strptime(str(self.start_time), "%H:%M:%S")
        ).seconds / 3600

    @property
    def get_overtime(self):
        ot = Decimal(self.employee.profile.hourly_rate) * Decimal(self.multiplier.multiplier) * Decimal(self.time_diff)
        return "%.2f" % round(ot, 3)

    def __str__(self):
        return f"${self.get_overtime} ({self.time_diff} hours) ({self.date}) {self.multiplier.multiplier}"

app/overtime/forms.py
from django import forms

from .models import TimeSheet


class TimeSheetCreateForm(forms.ModelForm):
    class Meta:
        model = TimeSheet
        fields = (
            "date",
            "reason",
            "start_time",
            "end_time",
            "multiplier",
        )
        widgets = {
            "reason": forms.Textarea(attrs={"rows": 4}),
            "date": forms.DateInput(attrs={"type": "date"}),
            "start_time": forms.DateInput(attrs={"type": "time"}),
            "end_time": forms.DateInput(attrs={"type": "time"}),
        }


class TimeSheetUpdateForm(forms.ModelForm):
    class Meta:
        model = TimeSheet
        fields = (
            "date",
            "reason",
            "start_time",
            "end_time",
            "multiplier",
        )
        widgets = {
            "reason": forms.Textarea(attrs={"rows": 4}),
            "date": forms.DateInput(attrs={"type": "date"}),
        }

app/overtime/views.py
from datetime import datetime

from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView
from users.models import UserProfile

from .forms import TimeSheetCreateForm, TimeSheetUpdateForm
from .models import TimeSheet


class TimeSheetListView(ListView):
    model = TimeSheet
    template_name = "overtime/timesheet_list.html"
    paginate_by = 30

    def get_context_data(self, *args, **kwargs):
        context = super(TimeSheetListView, self).get_context_data(*args, **kwargs)
        context["employee_list"] = UserProfile.objects.all()
        return context

    def get_queryset(self):
        queryset = TimeSheet.objects.filter(created_by=self.request.user).order_by(
            "date", "start_time"
        )
        employee = self.request.GET.get("employee")
        start_date = self.request.GET.get("start_date")
        # start_date = datetime.strptime(start_date_a, '%Y-%m-%d').date()
        end_date = self.request.GET.get("end_date")
        # end_date = datetime.strptime(end_date_a, '%Y-%m-%d').date()
        if start_date != "" and start_date is not None:
            if end_date != "" and end_date is not None:
                if employee != "" and employee is not None:
                    queryset = queryset.filter(
                        Q(id=employee)
                        | Q(
                            date__gte=datetime.strptime(start_date, "%Y-%m-%d").date(),
                            date__lte=datetime.strptime(end_date, "%Y-%m-%d").date(),
                        )
                    ).distinct()
        return queryset


# class TimeSheetFilterListView(ListView):
#     model = TimeSheet
#     template_name = "overtime/timesheet_filter_list.html"

#     def get_queryset(self):
#         queryset = TimeSheet.objects.all()
#         employee = self.request.GET.get("employee")
#         start_date = self.request.GET.get("start_date")
#         end_date = self.request.GET.get("end_date")
#         print(start_date, "start_date", end_date, "end_date")
#         if start_date or end_date or employee:
#             queryset = queryset.filter(
#                 Q(id=employee) | Q(date__range=[start_date, end_date])
#             ).distinct()
#             print(queryset, "queryset")
#         return queryset


class TimeSheetPendingApprovalListView(ListView):
    model = TimeSheet
    template_name = "overtime/timesheet_pending_approval_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list"] = TimeSheet.objects.filter(is_approved=False)
        # print('context', context["time_sheet_pending_approval"])
        return context


class TimeSheetCreateView(SuccessMessageMixin, CreateView):
    model = TimeSheet
    form_class = TimeSheetCreateForm
    success_message = "Your time sheet was added successfully"
    success_url = reverse_lazy("overtime:time-sheet-list")

    def form_valid(self, form):
        form.instance.employee = self.request.user
        form.instance.created_by = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class TimeSheetUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = TimeSheet
    form_class = TimeSheetUpdateForm
    success_message = "Your time sheet was updated successfully"
    success_url = reverse_lazy("overtime:time-sheet-list")

    def test_func(self):
        if self.request.user == self.get_object().created_by:
            return True
        return False

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class TimeSheetDeleteView(UserPassesTestMixin, SuccessMessageMixin, DeleteView):
    model = TimeSheet
    success_message = "Your time sheet was deleted"
    success_url = reverse_lazy("overtime:time-sheet-list")

    def test_func(self):
        if self.request.user == self.get_object().created_by:
            return True
        return False

app/templates/overtime/timesheet_confirm_delete.html
{% load crispy_forms_tags %}<head>
    <title>{{object}}</title>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
        crossorigin="anonymous">

    <!-- GoogleIcons -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <!-- GoogleFonts -->
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">

    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }
    </style>
</head>

<body>
    <div class="container py-5">
        <form class="col-lg-6 border shadow p-4 rounded-3 mx-auto"action=""
            method="post">
            {% csrf_token %}
            <p class="border-bottom">Are you sure you want to delete "{{ object }}"?</p>
            {{form|crispy}}
            <div class="my-3 text-end">
                <button title="delete" class="btn btn-sm btn-outline-danger"
                    type="submit"> <span class="material-symbols-outlined">
                        delete
                    </span></button>
                <button title="delete" class="btn btn-sm btn-outline-secondary"
                    type="submit"> <span class="material-symbols-outlined">
                        cancel
                    </span></button>
                    
            </div>
        </form>
    </div>
</body>

app/templates/overtime/timesheet_form.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}

{% block head_title %}
Add Time sheet
{% endblock head_title %}



{% block content %}
<div class="pt-4 pb-2 px-5 bg-info">
    <a title="back" class="text-decoration-none text-dark" href="{% url 'overtime:time-sheet-list' %}"><span
            class="material-symbols-outlined fs-1">
            arrow_back
        </span></a>
</div>
<h1 class="bg-warning text-bg-warning p-3 text-center">Add Time sheet</h1>
<div class="container">
    <div class="container pb-5">
        <div
            class="col-4 bg-light py-4 px-5 border rounded-4 shadow py-3 mx-auto border border-2 my-3">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <div class="my-3 text-end">
                    <button class="btn btn-sm px-5 btn-outline-dark"
                        type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/overtime/timesheet_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block head_title %}
Time sheets
{% endblock head_title %}

{% block content %}
<div class="min-vh-100">
    <div class="bg-warning px-5 pt-4 pb-3">
        <a class="text-dark"
            title="add time sheet"
            href="{% url 'overtime:time-sheet-create' %}"><span
                class="material-symbols-outlined fs-1">
                add
            </span></a>
    </div>

    <div class="px-3 py-5">
        <form class="border rounded-pill shadow p-4 mb-3 col-lg-8 mx-auto"
            action="{% url 'overtime:time-sheet-list' %}"
            method="get">
            <div class="d-flex justify-content-between">
                <div class="">
                    <label for="">Employee</label>
                    <select class="form-control-sm form-comtrol rounded-pill"
                        name="employee"
                        id="">
                        {% for object in employee_list %}
                        <option class="rounded-pill form-control"
                            value="{{object.pk}}">
                            {{object}}
                        </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="">
                    <input class="form-control form-control-sm rounded-pill"
                        type="date"
                        name="start_date"
                        placeholder="start date"
                        id="">
                </div>
                <div class="">
                    <input class="form-control form-control-sm rounded-pill"
                        type="date"
                        name="end_date"
                        placeholder="end date"
                        id="">
                </div>
                <div class="text-end">
                    <button class="btn btn-sm btn-outline-dark"
                        type="submit">Filter</button>
                </div>
            </div>


        </form>
        <div class="row border-bottom border-top mt-5 mb-3">
            <div class="col">
                <h1 class="display-4">Time sheets</h1>
            </div>
            <div class="col text-end">
                <span id="mySpan"
                    class="display-4"></span>
            </div>
        </div>
        <div class="my-2">
            {% include 'components/pagination.html' %}
        </div>
        <table class="table table-hover table-sm small">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th class="col-3" scope="col">Reason</th>
                    <th class="col-1" scope="col">Start/End</th>
                    <th class="col-1" scope="col">Multiplier</th>
                    <th class="col-1" class="col-1"scope="col">Employee</th>
                    <th scope="col">Created</th>
                    <th scope="col">Hours</th>
                    <th scope="col">Overtime</th>
                    <th scope="col">
                        <div class="text-center">
                            <span title="details"class="material-symbols-outlined">
                                more_vert
                            </span>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}

                <tr>
                    <th scope="row">{{forloop.counter}}</th>

                    <td>{{object.date}}</td>
                    <td title="{{object.reason}}">
                        {{object.reason|truncatechars:60}}</td>
                    <td>{{object.start_time}} - {{object.end_time}}</td>
                    <td>{{object.multiplier}}</td>
                    <td>{{object.created_by.profile}}</td>
                    <td>{{object.created_at|naturaltime}}</td>
                    <td>{{object.time_diff}} hrs</td>
                    <td id="get_overtime">XCD${{object.get_overtime}}</td>
                    <td>
                        <a class="text-primary"
                            data-bs-toggle="modal"
                            data-bs-target="#exampleModal{{object.pk}}">
                            <span title="details" class="material-symbols-outlined">
                                info
                            </span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="my-2">
            {% include 'components/pagination.html' %}
        </div>
    </div>
</div>

{% for object in object_list %}


<!-- Modal -->
<div class="modal fade"
    id="exampleModal{{object.pk}}"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="exampleModalLabel">{{object.created_by}}</h5>
                <button type="button"
                    title="close"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                XCD${{object.get_overtime}}
            </div>
            <div class="modal-footer">
                <a title="edit"
                    class="fs-3 text-warning"
                    href="{% url 'overtime:time-sheet-update' object.pk %}">
                    <span class="material-symbols-outlined">
                        edit
                    </span>
                </a>
                <a title="edit"
                    class="fs-3 text-danger"
                    href="{% url 'overtime:time-sheet-delete' object.pk %}">
                    <span class="material-symbols-outlined">
                        delete
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<script>
    const ot = document.querySelectorAll('#get_overtime');
    var i;
    var ot_array = [];
    for (i = 0; i < ot.length; i++) {
        const ot_each = ot[i].innerHTML;
        ot_slice = ot_each.slice(4)
        ot_float = parseFloat(ot_slice)
        ot_array.push(ot_float)
        //total = total +=
        console.log(ot_array)
    }
    var ot_array = ot_array
    var sum = 0;

    for (var i = 0; i < ot_array.length; i++) {
        sum += ot_array[i];
    }
    console.log(sum.toFixed(2))
    document.getElementById('mySpan').innerHTML = "XCD$" + sum.toFixed(2)
</script>

{% endblock content %}

app/templates/overtime/timesheet_pending_approval_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block head_title %}
Time sheets
{% endblock head_title %}



{% block content %}
<div class="vh-100">
    <div class="container py-5">
        <h1 class="border-bottom display-4">Pending Approval</h1>
        <table class="table table-hover table-sm small">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Date</th>
                    <th scope="col">Reason</th>
                    <th scope="col">Start/End</th>
                    <th scope="col">Multiplier</th>
                    <th scope="col">Employee</th>
                    <th scope="col">Created</th>
                    <th scope="col">
                        <span class="material-symbols-outlined">
                            more_vert
                        </span>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>

                    <td>{{object.date}}</td>
                    <td>{{object.reason}}</td>
                    <td>{{object.start_time}} - {{object.end_time}}</td>
                    <td>{{object.multiplier}}</td>
                    <td>{{object.created_by}}</td>
                    <td>{{object.created_at|naturaltime}}</td>

                    <td>
                        <a class="text-primaryt"
                            data-bs-toggle="modal"
                            data-bs-target="#exampleModal{{object.pk}}">
                            <span class="material-symbols-outlined">
                                info
                            </span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% for object in object_list %}


<!-- Modal -->
<div class="modal fade"
    id="exampleModal{{object.pk}}"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="exampleModalLabel">{{object.created_by}}</h5>
                <button type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal">Close</button>
                <button type="button"
                    class="btn btn-primary">Approve Overtime</button>
            </div>
        </div>
    </div>
</div>

{% endfor %}

{% endblock content %}