app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("overtime/", include("overtime.urls", namespace="overtime")),
    path('accounts/', include('allauth.urls')),
    path("meals/", include("meals.urls", namespace="meals")),
    path("forms/", include("forms.urls", namespace="forms")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/meals/urls.py
from django.urls import path

from . import views

app_name = "meals"

urlpatterns = [
    path("", views.MealListView.as_view(), name="meal-list"),
    path("detail/<int:pk>/", views.MealDetailView.as_view(), name="meal-detail"),
    path("update/<int:pk>/", views.MealUpdateView.as_view(), name="meal-update"),
    path("detail/<int:pk>/", views.MealDeleteView.as_view(), name="meal-delete"),
    path("create/", views.MealCreateView.as_view(), name="meal-create"),
]

app/overtime/urls.py
from django.urls import path

from . import views

app_name = "overtime"

urlpatterns = [
    path("", views.TimeSheetListView.as_view(), name="time-sheet-list"),
    path("create/", views.TimeSheetCreateView.as_view(), name="time-sheet-create"),
    path(
        "pending-approval/",
        views.TimeSheetPendingApprovalListView.as_view(),
        name="time-sheet-pending-approval",
    ),
    # path(
    #     "filter-list/",
    #     views.TimeSheetFilterListView.as_view(),
    #     name="time-sheet-filter-list",
    # ),
    path(
        "update/<int:pk>/",
        views.TimeSheetUpdateView.as_view(),
        name="time-sheet-update",
    ),
    path(
        "delete/<int:pk>/",
        views.TimeSheetDeleteView.as_view(),
        name="time-sheet-delete",
    ),
]

app/meals/models.py
from django.db import models
from users.models import User


class Meal(models.Model):
    employee = models.ForeignKey(
        User, related_name="meal_employees", on_delete=models.CASCADE
    )
    start_time = models.TimeField()
    end_time = models.TimeField()
    claimed = models.DecimalField(max_digits=9, decimal_places=2)
    location = models.CharField(max_length=200)
    purpose = models.TextField()
    updated_by = models.ForeignKey(
        User, related_name="meal_updated_by", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(
        User, related_name="meal_approved_by", on_delete=models.CASCADE, blank=True, null=True
    )

    def __str__(self):
        return f"{self.employee.profile} - (XCD${self.claimed})"

app/meals/forms.py
from django import forms

from .models import Meal


class MealCreateForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ("purpose", "location", "start_time", "end_time", "claimed")
        widgets = {
            "purpose": forms.Textarea(attrs={"rows": 4}),
            "start_time": forms.DateInput(attrs={"type": "time"}),
            "end_time": forms.DateInput(attrs={"type": "time"}),
            "claimed": forms.TextInput(attrs={"placeholder": "$25.00"}),
        }


class MealUpdateForm(forms.ModelForm):
    class Meta:
        model = Meal
        fields = ("purpose", "location", "start_time", "end_time", "claimed")
        widgets = {
            "purpose": forms.Textarea(attrs={"rows": 4}),
            "claimed": forms.TextInput(attrs={"placeholder": "$25.00"}),
        }

app/meals/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from .forms import MealCreateForm, MealUpdateForm
from .models import Meal


class MealListView(ListView):
    model = Meal


class MealDetailView(DetailView):
    model = Meal


class MealUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Meal
    form_class = MealUpdateForm
    success_message = "Your meal was updated successfully"
    success_url = reverse_lazy("meals:meal-list")

    def test_func(self):
        if self.request.user == self.get_object().employee:
            return True
        return False

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class MealCreateView(SuccessMessageMixin, CreateView):
    model = Meal
    form_class = MealCreateForm
    success_message = "Your meal was added successfully"
    success_url = reverse_lazy("meals:meal-list")

    def form_valid(self, form):
        form.instance.employee = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class MealDeleteView(SuccessMessageMixin, DeleteView):
    model = Meal
    success_message = "Your meal was deleted"
    success_url = reverse_lazy("meals:meal-list")

    def test_func(self):
        if self.request.user == self.get_object().created_by:
            return True
        return False

app/templates/meals/meal_form.html
{% extends 'base.html' %}


{% load crispy_forms_tags %}

{% block head_title %}
Add Meal
{% endblock head_title %}


{% block content %}
<div class="pt-4 pb-2 px-5 bg-info">
    <a title="back" class="text-decoration-none text-dark" href="{% url 'overtime:time-sheet-list' %}"><span
            class="material-symbols-outlined fs-1">
            arrow_back
        </span></a>
</div>
<h1 class="bg-warning text-bg-warning p-3 text-center">Add Meal</h1>
<div class="container">
    <div class="container pb-5">
        <div
            class="col-4 bg-light py-4 px-5 border rounded-4 shadow py-3 mx-auto border border-2 my-3">
            <form action=""
                method="post">
                {% csrf_token %}
                {{form|crispy}}
                <div class="my-3 text-end">
                    <button class="btn btn-sm px-5 btn-outline-dark"
                        type="submit">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

app/templates/meals/meal_list.html
{% extends 'base.html' %}

{% load humanize %}

{% block head_title %}
Meals
{% endblock head_title %}

{% block content %}
<div class="vh-100">
    <div class="bg-warning px-5 pt-4 pb-3">
        <a class="text-dark"
            title="add time sheet"
            href="{% url 'meals:meal-create' %}"><span
                class="material-symbols-outlined fs-1">
                add
            </span></a>
    </div>
    
    <div class="container py-5">
        <div class="row border-bottom border-top mt-5 mb-3">
            <div class="col">
                <h1 class="display-4">Meals</h1>
            </div>
            <div class="col text-end">
                <span id="mySpan"
                    class="display-4"></span>
            </div>
        </div>
        <table class="table table-hover table-sm small">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Employee</th>
                    <th scope="col">Purpose</th>
                    <th scope="col">Start/End</th>
                    <th scope="col">Created</th>
                    <th scope="col">Claim</th>
                    <th scope="col">
                        <div class="text-center">
                            <span class="material-symbols-outlined">
                                more_vert
                            </span>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                <tr>
                    <th scope="row">{{forloop.counter}}</th>
                    <td>{{object.employee.profile}}</td>
                    <td>{{object.purpose}}</td>
                    <td>{{object.start_time}} - {{object.end_time}}</td>
                    <td>{{object.created_at}}</td>
                    <td id="get_claim">XCD${{object.claimed}}</td>
                    <td>
                        <a class="text-primary"
                            data-bs-toggle="modal"
                            data-bs-target="#exampleModal{{object.pk}}">
                            <span class="material-symbols-outlined">
                                info
                            </span>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% for object in object_list %}


<!-- Modal -->
<div class="modal fade"
    id="exampleModal{{object.pk}}"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"
                    id="exampleModalLabel">{{object.employee.profile}}</h5>
                <button type="button"
                    title="close"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-body">
                XCD${{object.claimed}}
            </div>
            <div class="modal-footer">
                <a title="edit"
                    class="fs-3 text-warning"
                    href="{% url 'meals:meal-update' object.pk %}">
                    <span class="material-symbols-outlined">
                        edit
                    </span>
                </a>
                <a title="edit"
                    class="fs-3 text-danger"
                    href="{% url 'meals:meal-delete' object.pk %}">
                    <span class="material-symbols-outlined">
                        delete
                    </span>
                </a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<script>
    const ot = document.querySelectorAll('#get_claim');
    var i;
    var ot_array = [];
    for (i = 0; i < ot.length; i++) {
        const ot_each = ot[i].innerHTML;
        ot_slice = ot_each.slice(4)
        ot_float = parseFloat(ot_slice)
        ot_array.push(ot_float)
        //total = total +=
        console.log(ot_array)
    }
    var ot_array = ot_array
    var sum = 0;

    for (var i = 0; i < ot_array.length; i++) {
        sum += ot_array[i];
    }
    console.log(sum.toFixed(2))
    document.getElementById('mySpan').innerHTML = "XCD" + sum.toFixed(2)
</script>

{% endblock content %}