app/cf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("overtime/", include("overtime.urls", namespace="overtime")),
    path('accounts/', include('allauth.urls')),
    path("meals/", include("meals.urls", namespace="meals")),
    path("forms/", include("forms.urls", namespace="forms")),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/forms/urls.py
from django.urls import path

from . import views

app_name = "forms"


urlpatterns = [
    path("", views.FormListView.as_view(), name="form-list"),
]

app/meals/urls.py
from django.urls import path

from . import views

app_name = "meals"

urlpatterns = [
    path("", views.MealListView.as_view(), name="meal-list"),
    path("detail/<int:pk>/", views.MealDetailView.as_view(), name="meal-detail"),
    path("update/<int:pk>/", views.MealUpdateView.as_view(), name="meal-update"),
    path("detail/<int:pk>/", views.MealDeleteView.as_view(), name="meal-delete"),
    path("create/", views.MealCreateView.as_view(), name="meal-create"),
]

app/overtime/urls.py
from django.urls import path

from . import views

app_name = "overtime"

urlpatterns = [
    path("", views.TimeSheetListView.as_view(), name="time-sheet-list"),
    path("create/", views.TimeSheetCreateView.as_view(), name="time-sheet-create"),
    path(
        "pending-approval/",
        views.TimeSheetPendingApprovalListView.as_view(),
        name="time-sheet-pending-approval",
    ),
    # path(
    #     "filter-list/",
    #     views.TimeSheetFilterListView.as_view(),
    #     name="time-sheet-filter-list",
    # ),
    path(
        "update/<int:pk>/",
        views.TimeSheetUpdateView.as_view(),
        name="time-sheet-update",
    ),
    path(
        "delete/<int:pk>/",
        views.TimeSheetDeleteView.as_view(),
        name="time-sheet-delete",
    ),
]

app/users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("users/", views.UserListView.as_view(), name="user-list"),
    path("userprofiles/", views.UserProfileListView.as_view(), name="user-profile-list"),
    path("user/<int:pk>/", views.UserUpdateView.as_view(), name="user-update"),
    path(
        "user-profile/<slug:slug>/<int:pk>/",
        views.UserProfileUpdateView.as_view(),
        name="user-profile-update",
    ),
]

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1">
    <title>
        {% block head_title %}

        {% endblock head_title %}
    </title>
    <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
        crossorigin="anonymous">

    <!-- GoogleIcons -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />

    <!-- GoogleFonts -->
    <link rel="preconnect"
        href="https://fonts.googleapis.com">
    <link rel="preconnect"
        href="https://fonts.gstatic.com"
        crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap"
        rel="stylesheet">


    <style>
        html,
        body {
            font-family: 'Montserrat', sans-serif;
        }

        span>i {
            cursor: pointer;
        }
        td>a {
            cursor: pointer;
        }

        #alert-message {
            z-index: 99;
            position: absolute;
            right: 2%;
            top: 8%;
            animation: hideAnimation 0s ease-in 5s;
            animation-fill-mode: forwards;
        }

        @keyframes hideAnimation {
            to {
                visibility: hidden;
                width: 0;
                height: 0;
              }
        }

    </style>
</head>

<body>

    {% include 'components/nav_bar.html' %}

    {% block content %}

    {% endblock content %}
    
    {% include 'components/messages.html' %}


    {% include 'components/footer.html' %}


    <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.html
{% extends 'base.html' %}


{% block head_title %}
Home
{% endblock head_title %}


{% block content %}
<div class="display-3 bg-warning p-3">Home</div>

<div class="container py-5 vh-100">
    <div class="container py-5">
        <ol>
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'overtime:time-sheet-list' %}">
                    Overtime
                </a>
            </li>
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'meals:meal-list' %}">
                    Meals
                </a>
            </li>
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'users:user-list' %}">
                    Contacts
                </a>
            </li>
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'forms:form-list' %}">
                    Forms
                </a>
            </li>
            {% if request.user.is_admin %}
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'users:user-list' %}">
                    Users
                </a>
            </li>
            <li class="mb-2">
                <a class="fs-5 text-dark"
                    href="{% url 'users:user-profile-list' %}">
                    User Profiles
                </a>
            </li>
            {% endif %}
        </ol>
    </div>
</div>
{% endblock content %}